'use client';

import React, { useState, useEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useGSAP } from '@gsap/react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ArrowRight,
  ArrowUpRight,
  ShieldCheck,
  FileText,
  Search,
  Database,
  GitBranch,
  AlertTriangle,
  Scale,
  Cpu,
  Layers,
  ChevronDown,
  ExternalLink,
  Globe,
  Users,
  CheckCircle2,
  FileCheck,
  Zap,
  Sparkles
} from 'lucide-react';
import SignInModal from '@/components/SignInModal';
import Link from 'next/link';
import Lenis from 'lenis';

gsap.registerPlugin(ScrollTrigger);

// ─── FAQ DATA ──────────────────────────────────────────────────────────────────
interface FAQItem {
  q: string;
  a: string;
}

const FAQ_ITEMS: FAQItem[] = [
  {
    q: 'What can SYNAPS understand?',
    a: 'SYNAPS ingests PDFs, Word documents, scanned files, financial models, emails, spreadsheets, and organizational policies. It parses unstructured text, tables, images, and layout relationships with line-level accuracy.',
  },
  {
    q: 'Can SYNAPS read scanned documents?',
    a: 'Yes. SYNAPS features enterprise-grade OCR with layout-aware spatial text extraction, preserving table structures, signatures, and inline marginalia.',
  },
  {
    q: 'Can I search across multiple documents?',
    a: 'Yes. SYNAPS creates a cross-document semantic index. A single query searches across your entire repository, returning exact citations, page numbers, and highlighted passages.',
  },
  {
    q: 'Can SYNAPS compare contracts and identify changes?',
    a: 'SYNAPS compares contract versions across years or counterparty drafts, pinpointing modified liability caps, altered cure periods, jurisdiction shifts, and risk implications.',
  },
  {
    q: 'Can SYNAPS cite where an answer came from?',
    a: 'Every answer, summary, or recommendation generated by SYNAPS includes exact line-level evidence references pointing directly back to the source document.',
  },
  {
    q: 'Can teams share organizational knowledge?',
    a: 'Yes. SYNAPS provides multi-tenant workspaces with role-based access control (RBAC), allowing teams to build shared, persistent organizational memory while protecting sensitive files.',
  },
  {
    q: 'Can SYNAPS research external web sources?',
    a: 'Yes. When configured, SYNAPS can verify claims against live public registries, market data, and regulatory databases, connecting external research directly back to your internal documents.',
  },
  {
    q: 'How does SYNAPS protect organizational information?',
    a: 'SYNAPS enforces DPDP Act and SOC 2 Type II compliance standards. Zero customer data is ever used to train public AI models. All data is encrypted in transit (TLS 1.3) and at rest (AES-256).',
  },
];

// ─── MAIN PONDER EDITORIAL LANDING COMPONENT ───────────────────────────────────
export default function PonderEditorialSynapsLanding() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  // Core Idea Words
  const [activeWordIndex, setActiveWordIndex] = useState(0);
  const words = ['PDFs.', 'Contracts.', 'Reports.', 'Emails.', 'Research.', 'Spreadsheets.', 'Decisions.', 'Knowledge.'];

  // One Question Moment Queries
  const sampleQueries = [
    'What is risky in this contract?',
    'Compare this year agreement with 2025.',
    'Find every reference to indemnification caps.',
    'What did the board decide regarding expansion?',
    'Research market rate for SLA penalty clauses.',
  ];
  const [activeQueryIdx, setActiveQueryIdx] = useState(0);

  // How SYNAPS Works Active Step
  const [activeStep, setActiveStep] = useState(1);

  // Product Scene State
  const [selectedDocPage, setSelectedDocPage] = useState(12);

  // Agent Layer Active Demo
  const [activeAgent, setActiveAgent] = useState<'review' | 'research' | 'document' | 'decision'>('review');

  const containerRef = useRef<HTMLDivElement>(null);
  const heroRef = useRef<HTMLDivElement>(null);
  const heroHeadingRef = useRef<HTMLHeadingElement>(null);

  // Lenis Smooth Scroll Initialization
  useEffect(() => {
    const lenis = new Lenis({
      duration: 1.3,
      easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
      smoothWheel: true,
    });

    function raf(time: number) {
      lenis.raf(time);
      requestAnimationFrame(raf);
    }
    requestAnimationFrame(raf);

    return () => {
      lenis.destroy();
    };
  }, []);

  // One Question Auto Cycle
  useEffect(() => {
    const qInterval = setInterval(() => {
      setActiveQueryIdx((prev) => (prev + 1) % sampleQueries.length);
    }, 3800);
    return () => clearInterval(qInterval);
  }, []);

  // Core Idea Words Cycle
  useEffect(() => {
    const wInterval = setInterval(() => {
      setActiveWordIndex((prev) => (prev + 1) % words.length);
    }, 1800);
    return () => clearInterval(wInterval);
  }, []);

  // GSAP ScrollTrigger Animations
  useGSAP(
    () => {
      if (!containerRef.current) return;

      // Hero Scroll Scale & Parallax Effect
      if (heroRef.current && heroHeadingRef.current) {
        gsap.to(heroHeadingRef.current, {
          scale: 0.92,
          y: '-10vh',
          opacity: 0.7,
          ease: 'none',
          scrollTrigger: {
            trigger: heroRef.current,
            start: 'top top',
            end: 'bottom top',
            scrub: true,
          },
        });
      }

      // Editorial Masked Text Reveals
      const maskedTexts = gsap.utils.toArray<HTMLElement>('[data-mask-reveal]');
      maskedTexts.forEach((el) => {
        gsap.fromTo(
          el,
          { y: '100%', opacity: 0 },
          {
            y: '0%',
            opacity: 1,
            duration: 1.2,
            ease: 'power3.out',
            scrollTrigger: {
              trigger: el,
              start: 'top 88%',
              toggleActions: 'play none none reverse',
            },
          }
        );
      });

      // Section Fade-In Reveals
      const revealItems = gsap.utils.toArray<HTMLElement>('[data-editorial-reveal]');
      revealItems.forEach((item) => {
        gsap.fromTo(
          item,
          { opacity: 0, y: 40 },
          {
            opacity: 1,
            y: 0,
            duration: 1,
            ease: 'power3.out',
            scrollTrigger: {
              trigger: item,
              start: 'top 85%',
              toggleActions: 'play none none reverse',
            },
          }
        );
      });
    },
    { scope: containerRef }
  );

  return (
    <div ref={containerRef} className="min-h-screen bg-[#08080a] text-[#f5f5f7] font-sans selection:bg-blue-600/30 selection:text-blue-200 overflow-x-hidden antialiased">
      {/* ── 05 SCENE: NAVIGATION ────────────────────────────────────────────── */}
      <header className="fixed top-0 left-0 w-full z-50 px-6 sm:px-12 py-6 flex items-center justify-between backdrop-blur-md bg-[#08080a]/75 border-b border-white/5 transition-all">
        <div className="flex items-center gap-3 cursor-pointer group">
          <div className="w-8 h-8 rounded-lg bg-white/10 border border-white/15 flex items-center justify-center font-mono font-bold text-white text-base group-hover:border-blue-500 transition-colors">
            S
          </div>
          <span className="font-mono text-base font-bold tracking-widest text-white">SYNAPS</span>
        </div>

        <nav className="hidden md:flex items-center gap-10 font-mono text-xs text-neutral-400 tracking-wider">
          <a href="#product" className="hover:text-white transition-colors">PRODUCT</a>
          <a href="#capabilities" className="hover:text-white transition-colors">CAPABILITIES</a>
          <a href="#how-it-works" className="hover:text-white transition-colors">HOW IT WORKS</a>
          <a href="#enterprise" className="hover:text-white transition-colors">ENTERPRISE</a>
        </nav>

        <div className="flex items-center gap-4">
          <Link
            href="/dashboard/chat"
            className="hidden sm:inline-flex items-center gap-2 font-mono text-xs text-neutral-300 hover:text-white px-4 py-2 rounded.md border border-white/10 hover:border-white/20 transition-all"
          >
            <span>Open SYNAPS</span>
            <ArrowUpRight className="w-3.5 h-3.5 text-neutral-400" />
          </Link>

          <button
            onClick={() => setIsModalOpen(true)}
            className="px-5 py-2.5 rounded-md bg-white hover:bg-neutral-200 text-black font-mono text-xs font-semibold uppercase tracking-wider transition-all flex items-center gap-2"
          >
            <span>Enter SYNAPS</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>
      </header>

      {/* ── 06 & 07 SCENE: HERO — MAKE THIS FEEL LIKE A FILM ────────────────── */}
      <section ref={heroRef} className="min-h-screen pt-40 pb-24 px-6 sm:px-12 max-w-7xl mx-auto flex flex-col justify-between relative">
        <div className="space-y-8">
          <div className="overflow-hidden">
            <h1
              ref={heroHeadingRef}
              className="font-mono text-[clamp(3.5rem,9.5vw,9.5rem)] font-black text-white tracking-tighter leading-[0.88] uppercase"
            >
              INFORMATION <br />
              BECOMES <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-white via-neutral-200 to-blue-400">
                INTELLIGENCE.
              </span>
            </h1>
          </div>

          <div className="max-w-2xl text-neutral-400 text-lg sm:text-xl leading-relaxed font-sans font-normal" data-editorial-reveal>
            SYNAPS reads, connects, reasons through, and acts on the information your organization already has.
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-6 pt-12 border-t border-white/10" data-editorial-reveal>
          <button
            onClick={() => setIsModalOpen(true)}
            className="px-8 py-4 rounded-md bg-blue-600 hover:bg-blue-500 text-white font-mono text-xs font-bold uppercase tracking-widest transition-all flex items-center gap-3 shadow-[0_0_30px_rgba(0,85,255,0.3)]"
          >
            <span>Enter SYNAPS</span>
            <ArrowRight className="w-4 h-4" />
          </button>

          <a
            href="#core-idea"
            className="px-8 py-4 rounded-md border border-white/15 hover:border-white/30 text-neutral-300 hover:text-white font-mono text-xs font-semibold uppercase tracking-widest transition-all"
          >
            See how it works ↓
          </a>
        </div>
      </section>

      {/* ── 09 SCENE: THE CORE IDEA ───────────────────────────────────────────── */}
      <section id="core-idea" className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-16">
        <div className="space-y-4" data-editorial-reveal>
          <span className="font-mono text-xs text-blue-400 uppercase tracking-widest">// THE PROBLEM</span>
          <h2 className="font-mono text-[clamp(2.5rem,6.5vw,6.5rem)] font-bold text-white tracking-tight leading-[0.95]">
            Your organization already <br />
            has the answers. <br />
            <span className="text-neutral-500">They are just everywhere.</span>
          </h2>
        </div>

        {/* Dynamic Word Sequential Reveal */}
        <div className="p-8 sm:p-12 rounded-2xl border border-white/10 bg-[#0d0d11] flex flex-col md:flex-row items-center justify-between gap-8" data-editorial-reveal>
          <div className="space-y-2">
            <span className="font-mono text-xs text-neutral-500 uppercase tracking-widest">SCATTERED DATA FORMATS</span>
            <div className="font-mono text-4xl sm:text-6xl font-extrabold text-blue-400 tracking-tight transition-all duration-300">
              {words[activeWordIndex]}
            </div>
          </div>
          <div className="max-w-md text-neutral-400 text-sm sm:text-base leading-relaxed">
            Siloed in isolated cloud drives, email threads, and PDF archives. Synaps unifies them into one coherent, queryable evidentiary layer.
          </div>
        </div>
      </section>

      {/* ── 10 SCENE: THE SYNAPS TRANSFORMATION ──────────────────────────────── */}
      <section className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <span className="font-mono text-xs text-blue-400 uppercase tracking-widest">// THE TRANSFORMATION</span>
          <h2 className="font-mono text-3xl sm:text-5xl font-bold text-white tracking-tight">
            FROM UNSTRUCTURED FRAGMENTS TO AUDITABLE EVIDENCE.
          </h2>
        </div>

        <div className="grid md:grid-cols-5 gap-4 font-mono text-xs">
          <div className="p-6 rounded-xl border border-white/10 bg-[#0d0d11] space-y-3">
            <div className="text-neutral-500 font-bold">01 // INGEST</div>
            <div className="text-white font-bold text-sm">Contract Page</div>
            <p className="text-neutral-400 text-xs">Unstructured PDF / Image scan uploaded.</p>
          </div>

          <div className="p-6 rounded-xl border border-white/10 bg-[#0d0d11] space-y-3">
            <div className="text-neutral-500 font-bold">02 // PARSE</div>
            <div className="text-white font-bold text-sm">OCR Layer</div>
            <p className="text-neutral-400 text-xs">Layout-aware text and spatial extraction.</p>
          </div>

          <div className="p-6 rounded-xl border border-white/10 bg-[#0d0d11] space-y-3">
            <div className="text-neutral-500 font-bold">03 // UNDERSTAND</div>
            <div className="text-white font-bold text-sm">Semantic Mesh</div>
            <p className="text-neutral-400 text-xs">Context & clause entity classification.</p>
          </div>

          <div className="p-6 rounded-xl border border-white/10 bg-[#0d0d11] space-y-3">
            <div className="text-neutral-500 font-bold">04 // CONNECT</div>
            <div className="text-white font-bold text-sm">Cross-Reference</div>
            <p className="text-neutral-400 text-xs">Linked with policy & historical decisions.</p>
          </div>

          <div className="p-6 rounded-xl border border-blue-500/40 bg-blue-600/10 space-y-3">
            <div className="text-blue-400 font-bold">05 // REASON</div>
            <div className="text-white font-bold text-sm">Decision Insight</div>
            <p className="text-neutral-300 text-xs">100% evidence-backed executive answer.</p>
          </div>
        </div>
      </section>

      {/* ── 11 FEATURE STORY — 01: UNDERSTAND EVERYTHING ────────────────────── */}
      <section id="capabilities" className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <div className="font-mono text-6xl font-black text-blue-500">01</div>
          <h2 className="font-mono text-4xl sm:text-6xl font-bold text-white tracking-tight uppercase">
            UNDERSTAND <br /> EVERYTHING.
          </h2>
          <p className="max-w-2xl text-neutral-400 text-base sm:text-lg">
            SYNAPS reads documents in depth, including scanned pages, tables, images, layouts and OCR content, creating a searchable understanding of the material instead of forcing you to manually hunt through it.
          </p>
        </div>

        {/* Large Interactive Document UI */}
        <div className="p-6 sm:p-10 rounded-2xl border border-white/10 bg-[#0d0d11] space-y-6 shadow-2xl">
          <div className="flex items-center justify-between pb-4 border-b border-white/10 font-mono text-xs text-neutral-400">
            <div className="flex items-center gap-3">
              <FileText className="w-4 h-4 text-blue-400" />
              <span className="text-white font-bold">Enterprise_Vendor_Agreement_v4.pdf</span>
              <span className="bg-white/10 text-neutral-300 px-2 py-0.5 rounded">PAGE {selectedDocPage} OF 64</span>
            </div>
            <span className="text-blue-400 font-semibold">LAYOUT OCR VERIFIED</span>
          </div>

          <div className="grid md:grid-cols-12 gap-8 font-mono text-xs sm:text-sm">
            <div className="md:col-span-8 p-6 rounded-xl border border-white/10 bg-black/40 space-y-4 text-neutral-300 leading-relaxed">
              <div className="text-neutral-500 text-xs">Line 142 — Section 19.4 [INDEMNIFICATION]:</div>
              <p className="p-3 rounded bg-blue-600/10 border border-blue-500/30 text-white font-sans">"Supplier agrees to indemnify, defend, and hold harmless Customer against any losses exceeding <strong className="text-blue-300">$2,500,000 USD</strong> arising out of data protection breaches."</p>
              <div className="text-neutral-500 text-xs">Line 158 — Section 21.1 [GOVERNING LAW]:</div>
              <p className="p-3 rounded bg-white/5 border border-white/10">"This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware."</p>
            </div>

            <div className="md:col-span-4 p-5 rounded-xl border border-blue-500/30 bg-blue-600/10 space-y-3">
              <div className="text-blue-400 font-bold text-xs uppercase tracking-wider flex items-center gap-2">
                <ShieldCheck className="w-4 h-4" /> EVIDENCE INSIGHT
              </div>
              <p className="text-xs text-neutral-200">
                Indemnification cap is <strong className="text-white">$1.5M higher</strong> than standard Q2 compliance guidelines. Flagged for legal review.
              </p>
              <div className="pt-3 border-t border-white/10 text-[11px] text-neutral-400 flex items-center justify-between">
                <span>CONFIDENCE: 99.8%</span>
                <span className="text-blue-400 font-bold">AUDITED</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── 12 FEATURE STORY — 02: ASK ONCE. FIND THE ANSWER. ───────────────── */}
      <section className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <div className="font-mono text-6xl font-black text-blue-500">02</div>
          <h2 className="font-mono text-4xl sm:text-6xl font-bold text-white tracking-tight uppercase">
            ASK ONCE. <br /> FIND THE ANSWER.
          </h2>
        </div>

        <div className="p-6 sm:p-10 rounded-2xl border border-white/10 bg-[#0d0d11] space-y-6">
          <div className="p-4 rounded-xl border border-white/15 bg-black/60 font-mono text-sm text-white flex items-center justify-between">
            <span className="flex items-center gap-3">
              <Search className="w-4 h-4 text-blue-400" />
              <span>Query: "Find every mention of termination rights across all active contracts."</span>
            </span>
            <span className="text-xs text-blue-400 font-bold">4 RESULTS FOUND</span>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 font-mono text-xs">
            <div className="p-4 rounded-xl border border-white/10 bg-white/5 hover:border-blue-500/40 transition-all space-y-2">
              <div className="text-blue-400 font-bold">Document 01 — Page 12</div>
              <div className="text-white font-semibold">MSA_Acme_2026.pdf</div>
              <p className="text-neutral-400 text-xs">"30 days written notice required prior to annual renewal..."</p>
            </div>

            <div className="p-4 rounded-xl border border-white/10 bg-white/5 hover:border-blue-500/40 transition-all space-y-2">
              <div className="text-blue-400 font-bold">Document 03 — Page 47</div>
              <div className="text-white font-semibold">Vendor_SLA_Master.pdf</div>
              <p className="text-neutral-400 text-xs">"Immediate termination upon 3 consecutive SLA drops..."</p>
            </div>

            <div className="p-4 rounded-xl border border-white/10 bg-white/5 hover:border-blue-500/40 transition-all space-y-2">
              <div className="text-blue-400 font-bold">Document 07 — Page 63</div>
              <div className="text-white font-semibold">Cloud_Infra_Terms.pdf</div>
              <p className="text-neutral-400 text-xs">"90 days cure period for non-material breaches..."</p>
            </div>

            <div className="p-4 rounded-xl border border-white/10 bg-white/5 hover:border-blue-500/40 transition-all space-y-2">
              <div className="text-blue-400 font-bold">Document 11 — Page 18</div>
              <div className="text-white font-semibold">DPDP_Compliance.pdf</div>
              <p className="text-neutral-400 text-xs">"Termination clause automatically invoked upon data breach..."</p>
            </div>
          </div>
        </div>
      </section>

      {/* ── 13 FEATURE STORY — 03: CONNECT THE DOTS ──────────────────────────── */}
      <section className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <div className="font-mono text-6xl font-black text-blue-500">03</div>
          <h2 className="font-mono text-4xl sm:text-6xl font-bold text-white tracking-tight uppercase">
            CONNECT <br /> THE DOTS.
          </h2>
          <p className="max-w-2xl text-neutral-400 text-base sm:text-lg">
            Compare this year's agreement with last year's agreement and identify material changes automatically.
          </p>
        </div>

        <div className="p-6 sm:p-10 rounded-2xl border border-white/10 bg-[#0d0d11] space-y-6">
          <div className="grid md:grid-cols-2 gap-6 font-mono text-xs sm:text-sm">
            <div className="p-5 rounded-xl border border-red-500/30 bg-red-500/10 space-y-2">
              <div className="text-red-300 font-bold">2025 Master Agreement [OLD]</div>
              <p className="text-neutral-300 font-sans">"Liability capped at $1,000,000 USD. No data residency guarantee."</p>
            </div>

            <div className="p-5 rounded-xl border border-emerald-500/30 bg-emerald-500/10 space-y-2">
              <div className="text-emerald-300 font-bold">2026 Master Agreement [NEW]</div>
              <p className="text-neutral-300 font-sans">"Liability capped at 2.5x ARR ($2,500,000 USD). DPDP Act compliance included."</p>
            </div>
          </div>
        </div>
      </section>

      {/* ── 14 FEATURE STORY — 04: TURN INFORMATION INTO DECISIONS ───────────── */}
      <section className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <div className="font-mono text-6xl font-black text-blue-500">04</div>
          <h2 className="font-mono text-4xl sm:text-6xl font-bold text-white tracking-tight uppercase">
            TURN INFORMATION <br /> INTO DECISIONS.
          </h2>
        </div>

        <div className="p-6 sm:p-10 rounded-2xl border border-white/10 bg-[#0d0d11] space-y-6 font-mono text-xs sm:text-sm">
          <div className="text-white font-bold text-base">EXECUTIVE DECISION REVIEW // GLOBAL SUPPLY AGREEMENT</div>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 text-center">
            <div className="p-4 rounded-lg border border-white/10 bg-white/5"><div className="text-neutral-400 text-[10px]">RISK</div><div className="text-white font-bold mt-1">Medium</div></div>
            <div className="p-4 rounded-lg border border-white/10 bg-white/5"><div className="text-neutral-400 text-[10px]">SEVERITY</div><div className="text-amber-400 font-bold mt-1">Level 2</div></div>
            <div className="p-4 rounded-lg border border-white/10 bg-white/5"><div className="text-neutral-400 text-[10px]">EVIDENCE</div><div className="text-blue-400 font-bold mt-1">Section 14.2</div></div>
            <div className="p-4 rounded-lg border border-white/10 bg-white/5"><div className="text-neutral-400 text-[10px]">IMPACT</div><div className="text-white font-bold mt-1">+$1.5M Liability</div></div>
            <div className="p-4 rounded-lg border border-blue-500/40 bg-blue-600/10"><div className="text-blue-400 text-[10px]">RECOMMENDED</div><div className="text-blue-300 font-bold mt-1">Approve w/ Addendum</div></div>
          </div>
        </div>
      </section>

      {/* ── 15 FEATURE STORY — 05: RESEARCH BEYOND THE FILE ──────────────────── */}
      <section className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <div className="font-mono text-6xl font-black text-blue-500">05</div>
          <h2 className="font-mono text-4xl sm:text-6xl font-bold text-white tracking-tight uppercase">
            RESEARCH <br /> BEYOND THE FILE.
          </h2>
        </div>

        <div className="p-6 sm:p-10 rounded-2xl border border-white/10 bg-[#0d0d11] space-y-4 font-mono text-xs">
          <div className="flex items-center gap-2 text-blue-400 font-bold"><Globe className="w-4 h-4" /> LIVE WEB & REGULATORY VERIFICATION</div>
          <div className="p-4 rounded-xl border border-white/10 bg-black/40 space-y-2 text-neutral-300">
            <div>1. Extracted Claim: "Vendor certifies ISO 27001 compliance as of 2026."</div>
            <div className="text-blue-400">2. External Audit: Verified against International Accreditation Forum (IAF) database.</div>
            <div className="text-emerald-400 font-bold">3. Result: Valid certificate #IAF-994120 active through Nov 2027.</div>
          </div>
        </div>
      </section>

      {/* ── 16 FEATURE STORY — 06: REMEMBER FOR THE ORGANIZATION ─────────────── */}
      <section className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <div className="font-mono text-6xl font-black text-blue-500">06</div>
          <h2 className="font-mono text-4xl sm:text-6xl font-bold text-white tracking-tight uppercase">
            REMEMBER <br /> FOR THE ORGANIZATION.
          </h2>
        </div>

        <div className="p-6 sm:p-10 rounded-2xl border border-white/10 bg-[#0d0d11] space-y-4 font-mono text-xs">
          <div className="text-white font-bold text-sm">PERSISTENT ORGANIZATIONAL KNOWLEDGE RETRIEVAL</div>
          <div className="p-4 rounded-xl border border-white/10 bg-white/5 space-y-2 text-neutral-300">
            <div className="text-neutral-400">Query: "What did the board decide regarding Q3 cloud migration budget?"</div>
            <div className="text-white font-bold">Retrieved from Minutes_Q3_2026.pdf (Page 4): Approved $12M allocation with 15% contingency buffer.</div>
          </div>
        </div>
      </section>

      {/* ── 17 SCENE: THE "ONE QUESTION" MOMENT ──────────────────────────────── */}
      <section className="py-40 px-6 sm:px-12 max-w-5xl mx-auto text-center border-t border-white/10 space-y-8" data-editorial-reveal>
        <span className="font-mono text-xs text-blue-400 uppercase tracking-widest">// THE INTERACTION</span>
        <h2 className="font-mono text-5xl sm:text-8xl font-black text-white tracking-tighter uppercase">
          ASK ANYTHING.
        </h2>

        <div className="p-6 rounded-2xl border border-white/15 bg-[#0d0d11] max-w-2xl mx-auto font-mono text-sm text-left shadow-2xl space-y-4">
          <div className="flex items-center justify-between text-xs text-neutral-500 border-b border-white/10 pb-3">
            <span>SYNAPS INTELLIGENCE PROMPT</span>
            <span className="text-blue-400">READY</span>
          </div>
          <div className="text-white font-bold text-base sm:text-lg animate-pulse">
            "{sampleQueries[activeQueryIdx]}"
          </div>
        </div>
      </section>

      {/* ── 18 SCENE: HOW SYNAPS WORKS (VERTICAL EDITORIAL SEQUENCE) ─────────── */}
      <section id="how-it-works" className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-16" data-editorial-reveal>
        <div className="space-y-4">
          <span className="font-mono text-xs text-blue-400 uppercase tracking-widest">// ARCHITECTURE</span>
          <h2 className="font-mono text-4xl sm:text-6xl font-bold text-white tracking-tight">
            HOW SYNAPS WORKS.
          </h2>
        </div>

        <div className="space-y-8 font-mono">
          {[
            { num: '01', title: 'INGEST', desc: 'Documents enter SYNAPS via REST API, cloud connectors, or direct upload.' },
            { num: '02', title: 'UNDERSTAND', desc: 'OCR, structure, spatial layout, and semantic entity context are extracted.' },
            { num: '03', title: 'CONNECT', desc: 'Information is connected across documents, people, projects, and organizational knowledge.' },
            { num: '04', title: 'REASON', desc: 'SYNAPS answers questions, compares information, and evaluates decision risks.' },
            { num: '05', title: 'ACT', desc: 'Generate reports, research external data, retrieve evidence, and execute agent workflows.' },
          ].map((item, idx) => (
            <div
              key={item.num}
              onClick={() => setActiveStep(idx + 1)}
              className={`p-6 sm:p-8 rounded-2xl border transition-all cursor-pointer flex flex-col md:flex-row md:items-center justify-between gap-6 ${
                activeStep === idx + 1 ? 'border-blue-500 bg-blue-600/10 text-white shadow-xl' : 'border-white/10 bg-[#0d0d11] text-neutral-400 hover:border-white/20'
              }`}
            >
              <div className="flex items-center gap-6">
                <span className="text-2xl font-bold text-blue-400">{item.num}</span>
                <span className="text-xl font-bold tracking-wider text-white">{item.title}</span>
              </div>
              <p className="max-w-xl text-sm leading-relaxed text-neutral-300">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── 21 SCENE: AGENTS ─────────────────────────────────────────────────── */}
      <section className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <span className="font-mono text-xs text-blue-400 uppercase tracking-widest">// ORCHESTRATION</span>
          <h2 className="font-mono text-4xl sm:text-6xl font-bold text-white tracking-tight uppercase">
            FROM ANSWERS <br /> TO ACTION.
          </h2>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4 font-mono text-xs">
          {['Research Agent', 'Document Agent', 'Review Agent', 'Decision Agent', 'Knowledge Agent'].map((agentName, idx) => (
            <div key={agentName} className="p-5 rounded-xl border border-white/10 bg-[#0d0d11] hover:border-blue-500/40 transition-all space-y-3">
              <Cpu className="w-5 h-5 text-blue-400" />
              <div className="text-white font-bold">{agentName}</div>
              <p className="text-neutral-400 text-xs">Autonomous execution layer for enterprise workflows.</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── 22 SCENE: ENTERPRISE / TEAM INTELLIGENCE ─────────────────────────── */}
      <section id="enterprise" className="py-32 px-6 sm:px-12 max-w-7xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <span className="font-mono text-xs text-blue-400 uppercase tracking-widest">// SCALE</span>
          <h2 className="font-mono text-4xl sm:text-6xl font-bold text-white tracking-tight uppercase">
            PERSON → TEAM → ORGANIZATION.
          </h2>
        </div>

        <div className="grid md:grid-cols-3 gap-6 font-mono text-xs sm:text-sm">
          <div className="p-6 rounded-2xl border border-white/10 bg-[#0d0d11] space-y-3">
            <Users className="w-6 h-6 text-blue-400" />
            <div className="text-white font-bold text-base">Individual Workspace</div>
            <p className="text-neutral-400 text-xs leading-relaxed">Personal document OCR, search, summarization, and private decision reviews.</p>
          </div>

          <div className="p-6 rounded-2xl border border-white/10 bg-[#0d0d11] space-y-3">
            <Users className="w-6 h-6 text-cyan-400" />
            <div className="text-white font-bold text-base">Team Collaboration</div>
            <p className="text-neutral-400 text-xs leading-relaxed">Shared knowledge bases, team annotations, and cross-document proposal drafting.</p>
          </div>

          <div className="p-6 rounded-2xl border border-blue-500/40 bg-blue-600/10 space-y-3">
            <ShieldCheck className="w-6 h-6 text-blue-300" />
            <div className="text-white font-bold text-base">Enterprise Memory</div>
            <p className="text-neutral-200 text-xs leading-relaxed">SOC 2 Type II compliant persistent organizational intelligence with RBAC controls.</p>
          </div>
        </div>
      </section>

      {/* ── 23 SCENE: FAQ ACCORDION ──────────────────────────────────────────── */}
      <section className="py-32 px-6 sm:px-12 max-w-5xl mx-auto border-t border-white/10 space-y-12" data-editorial-reveal>
        <div className="space-y-4">
          <span className="font-mono text-xs text-blue-400 uppercase tracking-widest">// FREQUENTLY ASKED</span>
          <h2 className="font-mono text-4xl sm:text-5xl font-bold text-white tracking-tight">
            QUESTIONS & ANSWERS.
          </h2>
        </div>

        <div className="space-y-4 font-mono">
          {FAQ_ITEMS.map((item, idx) => (
            <div key={item.q} className="border-b border-white/10 pb-4">
              <button
                onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                className="w-full py-4 text-left font-bold text-base sm:text-lg text-white flex items-center justify-between hover:text-blue-400 transition-colors"
              >
                <span>{item.q}</span>
                <ChevronDown className={`w-5 h-5 transition-transform duration-300 ${openFaq === idx ? 'rotate-180 text-blue-400' : 'text-neutral-500'}`} />
              </button>
              {openFaq === idx && (
                <div className="pb-4 text-sm text-neutral-400 font-sans leading-relaxed">
                  {item.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* ── 24 SCENE: FINAL CTA ──────────────────────────────────────────────── */}
      <section className="py-40 px-6 sm:px-12 max-w-5xl mx-auto text-center border-t border-white/10 space-y-8" data-editorial-reveal>
        <h2 className="font-mono text-5xl sm:text-8xl font-black text-white tracking-tighter uppercase leading-none">
          STOP SEARCHING. <br />
          <span className="text-blue-400">START KNOWING.</span>
        </h2>

        <p className="text-neutral-400 text-base sm:text-lg max-w-xl mx-auto leading-relaxed">
          SYNAPS turns the information your organization already owns into intelligence you can act on.
        </p>

        <button
          onClick={() => setIsModalOpen(true)}
          className="px-10 py-5 rounded-md bg-white hover:bg-neutral-200 text-black font-mono text-xs font-bold uppercase tracking-widest shadow-[0_0_40px_rgba(255,255,255,0.2)] hover:scale-105 transition-all inline-flex items-center gap-3"
        >
          <span>Enter SYNAPS</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </section>

      {/* ── 25 SCENE: MINIMAL FOOTER ─────────────────────────────────────────── */}
      <footer className="py-12 px-6 sm:px-12 border-t border-white/10 font-mono text-xs text-neutral-500 flex flex-wrap items-center justify-between gap-6 max-w-7xl mx-auto">
        <div className="flex items-center gap-3">
          <span className="text-white font-bold">SYNAPS</span>
          <span>© 2026 SYNAPS ENTERPRISE INC.</span>
        </div>

        <div className="flex items-center gap-8 text-neutral-400">
          <Link href="/legal/terms" className="hover:text-white transition-colors">Terms</Link>
          <Link href="/legal/privacy" className="hover:text-white transition-colors">Privacy</Link>
          <Link href="/dashboard" className="hover:text-white transition-colors">Dashboard</Link>
        </div>
      </footer>

      {/* Sign In Modal */}
      <SignInModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} />
    </div>
  );
}
