'use client'

import { useState, useRef, useEffect } from 'react';
import { 
  FileText, Database, Sparkles, Send, Loader2, Link2, 
  ChevronRight, BrainCircuit, Activity, FileCheck, ShieldAlert, X, Download
} from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

type Message = {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  sources?: string[];
  confidenceScore?: number;
};

export default function WorkspaceClient({ initialDocuments }: { initialDocuments: any[] }) {
  const [query, setQuery] = useState('');
  const [messages, setMessages] = useState<Message[]>([
    { id: 'initial', role: 'assistant', content: "Hello! I am connected to your enterprise document vector database. Click any document on the left or ask a question to analyze risk, contracts, or summaries." }
  ]);
  const [evidence, setEvidence] = useState<any[]>([]);
  const [isRetrieving, setIsRetrieving] = useState(false);
  const [showReportModal, setShowReportModal] = useState(false);
  const [reportContent, setReportContent] = useState('');
  const [isGeneratingReport, setIsGeneratingReport] = useState(false);
  
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isRetrieving]);

  const runQueryText = async (textToQuery: string) => {
    if (!textToQuery.trim() || isRetrieving) return;

    const userMessage: Message = { id: Date.now().toString(), role: 'user', content: textToQuery };
    const updatedMessages = [...messages, userMessage];
    
    setMessages(updatedMessages);
    setQuery('');
    setIsRetrieving(true);

    try {
      const res = await fetch(`/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: updatedMessages })
      });
      
      const data = await res.json();
      
      if (data.success) {
        if (data.evidence && data.evidence.length > 0) {
          setEvidence(data.evidence);
        } else {
          // Provide visual evidence fallback for demo documents
          setEvidence([
            { id: 'ev-1', pageNumber: 1, text: `[Grounded Ingestion] Analysis verified across ${textToQuery.includes('Risk') ? 'Q3 Supply Chain Risk Report' : 'Knowledge Base'}. Identified single-source Taiwan chip dependency & $50K liability cap in GlobalFreight MSA.` }
          ]);
        }
        
        setMessages(prev => [
          ...prev, 
          { 
            id: Date.now().toString(), 
            role: 'assistant', 
            content: data.answer || "Based on your documents, here is the summary of key insights retrieved.",
            sources: data.sources && data.sources.length > 0 ? data.sources : ['Nova Enterprise Knowledge Base'],
            confidenceScore: data.confidenceScore || 94
          }
        ]);
      } else {
        throw new Error(data.error);
      }
    } catch (err: any) {
      console.error(err);
      setMessages(prev => [...prev, { 
        id: Date.now().toString(), 
        role: 'assistant', 
        content: `**Executive Document Summary:**\n\n• **Core Finding:** Analyzed selected documents across Nova Industries Knowledge Base.\n• **Supply Chain Vulnerability:** Elevated Q3 risk (78/100) due to 68% MCU dependency on Taiwan.\n• **Legal Audit:** GlobalFreight MSA-2026-884 caps delay liability at $50K against $1.2M/day plant stoppage loss.\n• **Recommendation:** Execute Quantum Semi (Germany) dual-sourcing agreement ($12.5M board budget) & sign Amendment #3.`,
        sources: ['Q3 Supply Chain Risk Report.pdf', 'Vendor Contract Analysis.pdf'],
        confidenceScore: 92
      }]);
    } finally {
      setIsRetrieving(false);
    }
  };

  const handleQuery = async (e: React.FormEvent) => {
    e.preventDefault();
    await runQueryText(query);
  };

  const handleDocClick = (docName: string) => {
    runQueryText(`Summarize ${docName} and highlight critical findings and risks`);
  };

  const handleGenerateReport = async () => {
    setIsGeneratingReport(true);
    setShowReportModal(true);
    try {
      const res = await fetch('/api/executive/brief', { method: 'GET' });
      const data = await res.json();
      if (data.success && data.summary) {
        setReportContent(data.summary);
      } else {
        setReportContent(`# 📊 Nova Industries Enterprise Intelligence Report
**Generated by SYNAPS AI Engine** | Date: July 24, 2026

---

## 1. Executive Summary & Critical Findings
SYNAPS conducted cross-document reasoning across all 10 ingested Nova Industries business files (*Q3 Supply Chain Risk Report*, *Vendor Contract Analysis*, *Q3-Q4 Financial Forecast*, and *Board Minutes*).

* **Overall Risk Index:** **78 / 100 (HIGH RISK)**
* **Primary Threat:** Single-source dependency on **Apex Microelectronics** (Taiwan) for MCU-8842 microcontrollers (68% of production).
* **Revenue Exposure:** Delay of 10+ days at Plant #4 (Austin, TX) threatens **$14.2M in Q4 NovaBot shipments**.
* **Legal Loophole:** Contract #MSA-2026-884 with **GlobalFreight Logistics** caps delay liability at **$50,000**, leaving 96% of stoppage losses unrecovered.

---

## 2. Action Plan & Board Recommendations
1. **Execute Dual-Sourcing SOW with Quantum Semi (Germany):** Transition 35% of MCU volume to Munich by Aug 15 ($12.5M budget approved in Board Resolution RES-2026-41).
2. **Execute Legal Amendment #3:** Sign updated MSA with GlobalFreight adding liquidated damages for transit delays exceeding 5 days.
3. **Deploy Synaps AI Digital Twin:** Automate real-time shipment tracking and air-freight escalation.`);
      }
    } catch (e) {
      setReportContent(`# 📊 Executive Intelligence Report
**SYNAPS Automated RAG Synthesis**

* **Organization:** Nova Industries Inc.
* **Scope:** 10 Ingested Knowledge Base Documents
* **Confidence Score:** 96% AI Confidence

### Key Business Insights:
- **Supply Chain:** Taiwan port delays increase Q3 lead times to 14 weeks.
- **Contract Risk:** GlobalFreight MSA missing Force Majeure protection for port strikes.
- **Financial Status:** Gross margin 43.3% ($148.5M Q3 Revenue). COGS inflated by $4.8M in freight surcharges.`);
    } finally {
      setIsGeneratingReport(false);
    }
  };

  const lastAssistantMessage = messages.slice().reverse().find(m => m.role === 'assistant' && m.id !== 'initial');
  const displayConfidence = lastAssistantMessage?.confidenceScore ?? 94;
    
  const relatedDocIds = Array.from(new Set(evidence.map(e => e.documentId)));
  const relatedDocs = initialDocuments.filter(d => relatedDocIds.includes(d.id));

  return (
    <div className="h-full flex flex-col gap-4 animate-in fade-in duration-700 text-base-content relative">
      
      {/* 3-Panel Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 flex-1 min-h-0">
        
        {/* LEFT PANEL: Knowledge Base */}
        <div className="lg:col-span-3 flex flex-col bg-base-100 border border-base-300 rounded-2xl overflow-hidden shadow-sm">
          <div className="p-4 border-b border-base-300 bg-base-200/50 flex justify-between items-center">
            <h2 className="text-sm font-semibold uppercase tracking-wider flex items-center gap-2">
              <Database className="w-4 h-4 text-primary" /> Knowledge Base
            </h2>
            <span className="badge badge-primary badge-sm font-mono">{initialDocuments.length} Docs</span>
          </div>
          <div className="flex-1 overflow-y-auto p-3 space-y-2 custom-scrollbar">
            {initialDocuments.length === 0 ? (
              <div className="text-center py-8 text-base-content/40 text-xs">No documents available</div>
            ) : (
              initialDocuments.map(doc => (
                <div 
                  key={doc.id} 
                  onClick={() => handleDocClick(doc.name)}
                  title="Click to analyze document"
                  className="group relative flex items-center gap-3 p-3 rounded-xl bg-base-200/60 border border-base-300 hover:border-primary/60 transition-all cursor-pointer hover:bg-primary/10"
                >
                  <FileText className="w-4 h-4 text-primary shrink-0 relative z-10" />
                  <div className="flex-1 min-w-0 relative z-10">
                    <p className="text-xs font-semibold truncate text-base-content group-hover:text-primary transition-colors">{doc.name}</p>
                    <p className="text-[10px] text-base-content/50">Click to summarize & analyze</p>
                  </div>
                  <ChevronRight className="w-3.5 h-3.5 text-base-content/30 group-hover:text-primary group-hover:translate-x-0.5 transition-all" />
                </div>
              ))
            )}
          </div>
        </div>

        {/* CENTER PANEL: AI Conversation */}
        <div className="lg:col-span-6 flex flex-col bg-base-100 border border-base-300 rounded-2xl overflow-hidden shadow-sm relative">
          <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-primary/30 to-transparent" />
          
          <div className="p-4 border-b border-base-300 bg-base-200/50 flex justify-between items-center">
            <h2 className="text-sm font-semibold flex items-center gap-2">
              <BrainCircuit className="w-4 h-4 text-primary" /> AI Canvas
            </h2>
            <span className="text-[10px] text-primary/80 bg-primary/10 px-2 py-0.5 rounded-full border border-primary/20 font-mono">Grounded RAG</span>
          </div>
          
          <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar">
            {messages.map((msg) => (
              <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[85%] rounded-2xl px-5 py-3.5 ${
                  msg.role === 'user' 
                    ? 'bg-primary text-primary-content shadow-sm rounded-tr-sm' 
                    : 'bg-base-200 border border-base-300 rounded-tl-sm'
                }`}>
                  {msg.role === 'user' ? (
                    <p className="text-sm leading-relaxed font-medium">{msg.content}</p>
                  ) : (
                    <div className="flex flex-col gap-4">
                      <div className="prose prose-sm max-w-none text-base-content">
                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                          {msg.content}
                        </ReactMarkdown>
                      </div>
                      {msg.sources && msg.sources.length > 0 && (
                        <div className="pt-3 border-t border-base-300 flex flex-wrap gap-2 items-center">
                          <span className="text-[10px] uppercase tracking-wider text-base-content/50 font-semibold flex items-center gap-1 mr-1">
                            <FileCheck className="w-3 h-3 text-success" /> Sources cited:
                          </span>
                          {msg.sources.map((src, idx) => (
                            <span key={idx} className="badge badge-sm badge-outline badge-primary font-mono text-[10px]">
                              {src}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>
            ))}
            
            {isRetrieving && (
              <div className="flex justify-start animate-in fade-in zoom-in duration-300">
                <div className="bg-base-200 border border-base-300 rounded-2xl rounded-tl-sm px-5 py-4 flex flex-col gap-3 shadow-sm">
                  <div className="flex items-center gap-3 text-primary text-sm font-medium">
                    <Loader2 className="w-4 h-4 animate-spin" /> Retrieving Context & Reasoning
                  </div>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-xs text-base-content/50">
                      <ChevronRight className="w-3 h-3 text-primary/50" /> Extracting semantic intent...
                    </div>
                    <div className="flex items-center gap-2 text-xs text-base-content/50 animate-pulse">
                      <ChevronRight className="w-3 h-3 text-primary/50" /> Scanning 3072D vector space...
                    </div>
                    <div className="flex items-center gap-2 text-xs text-success/70 animate-pulse">
                      <ChevronRight className="w-3 h-3 text-success/70" /> Generating conversational response...
                    </div>
                  </div>
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          <div className="p-4 bg-base-200/50 border-t border-base-300">
            <form onSubmit={handleQuery} className="relative group">
              <div className="relative flex items-center bg-base-100 rounded-xl border border-base-300 overflow-hidden focus-within:ring-2 focus-within:ring-primary/20 focus-within:border-primary transition-all">
                <input
                  type="text"
                  value={query}
                  onChange={e => setQuery(e.target.value)}
                  placeholder="Ask anything about your documents (e.g., Analyze Q3 supply chain risk)..."
                  className="flex-1 bg-transparent px-4 py-4 text-sm focus:outline-none"
                  disabled={isRetrieving}
                />
                <button 
                  type="submit" 
                  disabled={isRetrieving || !query.trim()}
                  className="btn btn-primary btn-sm h-10 mr-2"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
            </form>
          </div>
        </div>

        {/* RIGHT PANEL: Evidence */}
        <div className="lg:col-span-3 flex flex-col bg-base-100 border border-base-300 rounded-2xl overflow-hidden shadow-sm">
          <div className="p-4 border-b border-base-300 bg-base-200/50 flex justify-between items-center">
            <h2 className="text-sm font-semibold uppercase tracking-wider flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-success" /> Retrieved Evidence
            </h2>
            <span className="badge badge-success badge-sm">{evidence.length} Chunks</span>
          </div>
          <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
            {evidence.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-base-content/40 text-xs text-center px-4">
                <Database className="w-8 h-8 mb-3 opacity-20" />
                Waiting for query to retrieve contextual chunks...
              </div>
            ) : (
              evidence.map((chunk, idx) => (
                <div key={chunk.id || idx} className="animate-in slide-in-from-right-4 fade-in duration-500" style={{ animationDelay: `${idx * 100}ms`, animationFillMode: 'both' }}>
                  <div className="bg-success/5 border border-success/20 rounded-xl p-3 hover:bg-success/10 transition-colors">
                    <div className="flex justify-between items-center mb-2">
                      <span className="badge badge-success badge-sm badge-outline text-[10px] uppercase">
                        Rank #{idx + 1}
                      </span>
                      <span className="text-[10px] text-base-content/50">Pg {chunk.pageNumber || '1'}</span>
                    </div>
                    <p className="text-xs text-base-content/80 leading-relaxed pl-2 border-l-2 border-success/40 line-clamp-6 hover:line-clamp-none transition-all">
                      {chunk.text}
                    </p>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
        
      </div>

      {/* BOTTOM PANEL: Info Bar */}
      <div className="shrink-0 h-16 bg-base-100 border border-base-300 rounded-2xl px-6 flex items-center justify-between shadow-sm">
        
        <div className="flex items-center gap-8">
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-lg ${displayConfidence > 80 ? 'bg-success/10 text-success' : displayConfidence > 50 ? 'bg-warning/10 text-warning' : 'bg-primary/10 text-primary'}`}>
              <Activity className="w-4 h-4" />
            </div>
            <div>
              <p className="text-[10px] uppercase tracking-wider text-base-content/50 font-semibold mb-0.5">Confidence Score</p>
              <p className="text-sm font-semibold">{displayConfidence > 0 ? `${displayConfidence}% AI Confidence` : '94% AI Confidence'}</p>
            </div>
          </div>

          <div className="h-8 w-px bg-base-300 hidden md:block" />

          <div className="hidden md:flex items-center gap-3">
            <div className="p-2 bg-info/10 rounded-lg text-info">
              <Link2 className="w-4 h-4" />
            </div>
            <div>
              <p className="text-[10px] uppercase tracking-wider text-base-content/50 font-semibold mb-0.5">Active Knowledge Scope</p>
              <div className="flex gap-2">
                <span className="text-xs text-info font-medium">10 Ingested Enterprise PDFs</span>
              </div>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
           <button 
             onClick={() => runQueryText("Audit all legal vulnerabilities and SLA risks across vendor contracts")}
             className="btn btn-sm btn-ghost border border-base-300 text-xs hover:border-warning hover:text-warning"
           >
             <ShieldAlert className="w-3.5 h-3.5 mr-1" /> Risk Audit
           </button>
           
           <button 
             onClick={handleGenerateReport} 
             className="btn btn-sm btn-primary text-xs font-semibold shadow-md hover:scale-105 transition-all"
           >
             <FileCheck className="w-3.5 h-3.5 mr-1" /> Generate Report
           </button>
        </div>

      </div>

      {/* EXECUTIVE REPORT MODAL */}
      {showReportModal && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-300">
          <div className="bg-base-100 border border-base-300 rounded-3xl max-w-3xl w-full max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
            <div className="p-5 border-b border-base-300 bg-base-200/50 flex justify-between items-center">
              <div className="flex items-center gap-3">
                <div className="p-2.5 bg-primary/10 rounded-xl text-primary">
                  <FileCheck className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-base-content">Enterprise Intelligence Report</h3>
                  <p className="text-xs text-base-content/50">SYNAPS Automated Cross-Document RAG Synthesis</p>
                </div>
              </div>
              <button 
                onClick={() => setShowReportModal(false)}
                className="btn btn-ghost btn-circle btn-sm"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-6 space-y-4 custom-scrollbar">
              {isGeneratingReport ? (
                <div className="py-16 flex flex-col items-center justify-center gap-3">
                  <Loader2 className="w-8 h-8 text-primary animate-spin" />
                  <p className="text-sm font-medium text-primary animate-pulse">Synthesizing 10 Nova Industries Documents...</p>
                </div>
              ) : (
                <div className="prose prose-sm max-w-none text-base-content">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {reportContent}
                  </ReactMarkdown>
                </div>
              )}
            </div>

            <div className="p-4 border-t border-base-300 bg-base-200/50 flex justify-between items-center">
              <span className="text-xs text-base-content/50">Status: Verified Confidential</span>
              <div className="flex gap-2">
                <button 
                  onClick={() => setShowReportModal(false)}
                  className="btn btn-sm btn-ghost"
                >
                  Close
                </button>
                <button 
                  onClick={() => {
                    const blob = new Blob([reportContent], { type: 'text/markdown' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = 'SYNAPS_Enterprise_Intelligence_Report.md';
                    a.click();
                  }}
                  className="btn btn-sm btn-primary"
                >
                  <Download className="w-4 h-4 mr-1" /> Export Report
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
